export type BibleTextResult = {
  text: string;
  reference: string;
};

export const BOOK_MAP: Record<string, string> = {
  // Antiguo Testamento — español
  Gén: 'GEN',
  Génesis: 'GEN',
  Gen: 'GEN',
  Genesis: 'GEN',
  Éx: 'EXO',
  Éxodo: 'EXO',
  Ex: 'EXO',
  Exo: 'EXO',
  Exodus: 'EXO',
  Lev: 'LEV',
  Levítico: 'LEV',
  Leviticus: 'LEV',
  Núm: 'NUM',
  Números: 'NUM',
  Num: 'NUM',
  Numbers: 'NUM',
  Deut: 'DEU',
  Deuteronomio: 'DEU',
  Deu: 'DEU',
  Deuteronomy: 'DEU',
  Jos: 'JOS',
  Josué: 'JOS',
  Josh: 'JOS',
  Joshua: 'JOS',
  Jue: 'JDG',
  Jueces: 'JDG',
  Judg: 'JDG',
  Judges: 'JDG',
  Rut: 'RUT',
  Ruth: 'RUT',
  '1Sam': '1SA',
  '1 Sam': '1SA',
  '1 Samuel': '1SA',
  '2Sam': '2SA',
  '2 Sam': '2SA',
  '2 Samuel': '2SA',
  '1Rey': '1KI',
  '1 Rey': '1KI',
  '1 Reyes': '1KI',
  '1Kgs': '1KI',
  '1 Kgs': '1KI',
  '1 Kings': '1KI',
  '2Rey': '2KI',
  '2 Rey': '2KI',
  '2 Reyes': '2KI',
  '2Kgs': '2KI',
  '2 Kgs': '2KI',
  '2 Kings': '2KI',
  '1Cr': '1CH',
  '1 Cr': '1CH',
  '1 Crónicas': '1CH',
  '1Chr': '1CH',
  '1 Chr': '1CH',
  '1 Chronicles': '1CH',
  '2Cr': '2CH',
  '2 Cr': '2CH',
  '2 Crónicas': '2CH',
  '2Chr': '2CH',
  '2 Chr': '2CH',
  '2 Chronicles': '2CH',
  Esd: 'EZR',
  Esdras: 'EZR',
  Ezra: 'EZR',
  Neh: 'NEH',
  Nehemías: 'NEH',
  Nehemiah: 'NEH',
  Est: 'EST',
  Ester: 'EST',
  Esth: 'EST',
  Esther: 'EST',
  Job: 'JOB',
  Salm: 'PSA',
  Salmos: 'PSA',
  Sal: 'PSA',
  Ps: 'PSA',
  Psa: 'PSA',
  Psalms: 'PSA',
  Prov: 'PRO',
  Proverbios: 'PRO',
  Proverbs: 'PRO',
  Ecl: 'ECC',
  Eclesiastés: 'ECC',
  Eccl: 'ECC',
  Ecclesiastes: 'ECC',
  Cnt: 'SNG',
  Cantares: 'SNG',
  Song: 'SNG',
  SOS: 'SNG',
  Is: 'ISA',
  Isaías: 'ISA',
  Isa: 'ISA',
  Isaiah: 'ISA',
  Jer: 'JER',
  Jeremías: 'JER',
  Jeremiah: 'JER',
  Lam: 'LAM',
  Lamentaciones: 'LAM',
  Lamentations: 'LAM',
  Ez: 'EZK',
  Ezequiel: 'EZK',
  Ezek: 'EZK',
  Ezekiel: 'EZK',
  Dan: 'DAN',
  Daniel: 'DAN',
  Os: 'HOS',
  Oseas: 'HOS',
  Hos: 'HOS',
  Hosea: 'HOS',
  Jl: 'JOL',
  Joel: 'JOL',
  Am: 'AMO',
  Amós: 'AMO',
  Amos: 'AMO',
  Abd: 'OBA',
  Abdías: 'OBA',
  Obad: 'OBA',
  Obadiah: 'OBA',
  Jon: 'JON',
  Jonás: 'JON',
  Jonah: 'JON',
  Miq: 'MIC',
  Miqueas: 'MIC',
  Mic: 'MIC',
  Micah: 'MIC',
  Nah: 'NAM',
  Nahúm: 'NAM',
  Nahum: 'NAM',
  Hab: 'HAB',
  Habacuc: 'HAB',
  Habakkuk: 'HAB',
  Sof: 'ZEP',
  Sofonías: 'ZEP',
  Zeph: 'ZEP',
  Zephaniah: 'ZEP',
  Hag: 'HAG',
  Hageo: 'HAG',
  Haggai: 'HAG',
  Zac: 'ZEC',
  Zacarías: 'ZEC',
  Zech: 'ZEC',
  Zechariah: 'ZEC',
  Mal: 'MAL',
  Malaquías: 'MAL',
  Malachi: 'MAL',
  // Nuevo Testamento — español
  Mt: 'MAT',
  Mateo: 'MAT',
  Matt: 'MAT',
  Matthew: 'MAT',
  Mr: 'MRK',
  Marcos: 'MRK',
  Mark: 'MRK',
  Lc: 'LUK',
  Lucas: 'LUK',
  Luke: 'LUK',
  Jn: 'JHN',
  Juan: 'JHN',
  John: 'JHN',
  He: 'ACT',
  Hechos: 'ACT',
  Acts: 'ACT',
  Rom: 'ROM',
  Romanos: 'ROM',
  Romans: 'ROM',
  '1Cor': '1CO',
  '1 Cor': '1CO',
  '1 Corintios': '1CO',
  '1 Corinthians': '1CO',
  '2Cor': '2CO',
  '2 Cor': '2CO',
  '2 Corintios': '2CO',
  '2 Corinthians': '2CO',
  Gál: 'GAL',
  Gálatas: 'GAL',
  Gal: 'GAL',
  Galatians: 'GAL',
  Ef: 'EPH',
  Efesios: 'EPH',
  Eph: 'EPH',
  Ephesians: 'EPH',
  Fil: 'PHP',
  Filipenses: 'PHP',
  Phil: 'PHP',
  Philippians: 'PHP',
  Col: 'COL',
  Colosenses: 'COL',
  Colossians: 'COL',
  '1Tes': '1TH',
  '1 Tes': '1TH',
  '1 Tesalonicenses': '1TH',
  '1Thess': '1TH',
  '1 Thess': '1TH',
  '1 Thessalonians': '1TH',
  '2Tes': '2TH',
  '2 Tes': '2TH',
  '2 Tesalonicenses': '2TH',
  '2Thess': '2TH',
  '2 Thess': '2TH',
  '2 Thessalonians': '2TH',
  '1Tim': '1TI',
  '1 Tim': '1TI',
  '1 Timoteo': '1TI',
  '1 Timothy': '1TI',
  '2Tim': '2TI',
  '2 Tim': '2TI',
  '2 Timoteo': '2TI',
  '2 Timothy': '2TI',
  Tit: 'TIT',
  Tito: 'TIT',
  Titus: 'TIT',
  Flm: 'PHM',
  Filemón: 'PHM',
  Philem: 'PHM',
  Philemon: 'PHM',
  Heb: 'HEB',
  Hebreos: 'HEB',
  Hebrews: 'HEB',
  Stg: 'JAS',
  Santiago: 'JAS',
  Jas: 'JAS',
  James: 'JAS',
  '1Ped': '1PE',
  '1 Ped': '1PE',
  '1 Pedro': '1PE',
  '1Pet': '1PE',
  '1 Pet': '1PE',
  '1 Peter': '1PE',
  '2Ped': '2PE',
  '2 Ped': '2PE',
  '2 Pedro': '2PE',
  '2Pet': '2PE',
  '2 Pet': '2PE',
  '2 Peter': '2PE',
  '1Jn': '1JN',
  '1 Jn': '1JN',
  '1 Juan': '1JN',
  '1John': '1JN',
  '1 John': '1JN',
  '2Jn': '2JN',
  '2 Jn': '2JN',
  '2 Juan': '2JN',
  '2John': '2JN',
  '2 John': '2JN',
  '3Jn': '3JN',
  '3 Jn': '3JN',
  '3 Juan': '3JN',
  '3John': '3JN',
  '3 John': '3JN',
  Jud: 'JUD',
  Judas: 'JUD',
  Jude: 'JUD',
  Ap: 'REV',
  Apocalipsis: 'REV',
  Rev: 'REV',
  Revelation: 'REV',
};

export async function fetchBibleText(
  verseRef: string,
  version = 'rvr1960',
): Promise<BibleTextResult> {
  const slug = encodeURIComponent(verseRef.trim());
  const res = await fetch(`/api/bible?ref=${slug}&version=${version}`);
  if (!res.ok) {
    const err = (await res.json().catch(() => ({}))) as { error?: string };
    throw new Error(err.error ?? 'No se pudo cargar el texto bíblico');
  }
  const data = (await res.json()) as { text: string; reference: string };
  return { text: data.text, reference: data.reference };
}
