// ── Frases generadas automáticamente desde el archivo MD de ICT ──────────────
// NO editar manualmente — regenerar desde el script si se actualiza el MD

export const FRASES_MOTIVACIONALES: string[] = [
  'Hola 👋 Cami!! Empieza el día subiendo al monte con Papito Dios.',
  'Hola 🌞! Dios preparó un nuevo amanecer para ti.',
  'Hoy puede ser el mejor momento para escuchar la voz de Dios.',
  'Hola ✨! Solo necesitas unos minutos para llenar tu corazón de paz.',
  'Papito Dios está esperando compartir contigo este momento especial.',
  'Tu devocional de hoy puede cambiar completamente tu día.',
  'Recuerda: Dios nunca deja de pensar en ti.',
  'Hola 💙! Haz una pausa y deja que Dios abrace tu corazón.',
  'Jesús quiere caminar contigo hoy.',
  'Todo lo puedes en Cristo que te fortalece.',
  'Dios sigue escribiendo una historia hermosa contigo.',
  'Unos minutos con Dios pueden darte fuerzas para todo el día.',
  'Hola ☀️! Dios tiene algo especial para decirte hoy.',
  'Tu alma también necesita alimentarse.',
  'El cielo está atento a tus oraciones.',
  'Dios conoce cada una de tus luchas.',
  'Hoy es un buen día para acercarte más a Dios.',
  'Respira profundo… Dios sigue contigo.',
  'Tu tiempo con Dios nunca es una pérdida de tiempo.',
  'Papá Dios quiere darte descanso hoy.',
  'Aún en medio del caos, Dios sigue siendo paz.',
  'Dios no se ha olvidado de ti.',
  'Hola 🌻! Hay esperanza nueva para ti hoy.',
  'Jesús sigue tocando la puerta de tu corazón.',
  'Dale a Dios los primeros minutos de tu día.',
  'Dios puede hacer florecer lo que creías perdido.',
  'La presencia de Dios cambia todo.',
  'Hoy no estás solo/a.',
  'Hola 💫! Dios ya está obrando aunque no lo veas.',
  'Tu fe puede mover montañas.',
  'Dios escucha incluso las oraciones silenciosas.',
  'Hoy puede comenzar una nueva etapa contigo y Dios.',
  'Papito Dios quiere sentarse contigo hoy.',
  'La Biblia tiene respuestas para tu corazón.',
  'Cada día con Dios trae nuevas misericordias.',
  'Jesús sigue siendo refugio seguro.',
  'Hola 🌈! Dios tiene promesas para ti.',
  'Tu vida tiene propósito.',
  'Dios puede sanar hasta lo más profundo.',
  'No te rindas, Dios sigue peleando por ti.',
  'Tu devocional es una semilla para tu futuro.',
  'Dios te ama más de lo que imaginas.',
  'Hola 💖! Hay gracia suficiente para hoy.',
  'Dios transforma lágrimas en testimonios.',
  'Tu historia todavía no termina.',
  'Con Dios siempre hay esperanza.',
  'Dios sigue siendo fiel.',
  'Hoy es un gran día para volver a empezar.',
  'Dios está más cerca de lo que piensas.',
  'Tu corazón necesita escuchar a Dios hoy.',
  'Dios quiere darte dirección.',
  'La paz de Dios puede llenar tu mente.',
  'Hola 🙌! Dios ya preparó fuerzas nuevas para ti.',
  'Nunca subestimes un momento con Dios.',
  'Dios puede convertir tus pruebas en victoria.',
  'Él conoce tus cargas.',
  'Tu fe está creciendo incluso en silencio.',
  'Dios no llega tarde.',
  'Hoy puedes descansar en Sus promesas.',
  'Hola 🌟! El amor de Dios nunca falla.',
  'Dios sigue haciendo milagros.',
  'Él puede renovar tu corazón.',
  'Un devocional hoy, una vida transformada mañana.',
  'Dios siempre tiene la última palabra.',
  'Él sigue guiando tus pasos.',
  'Tu oración sí tiene poder.',
  'Dios puede darte sabiduría hoy.',
  'Hola 💙! Tómate un momento para hablar con Jesús.',
  'Tu alma necesita este tiempo especial.',
  'Dios sigue cuidando de ti.',
  'Jesús puede traer calma a tus tormentas.',
  'La fe vence el miedo.',
  'Dios sigue levantando corazones cansados.',
  'Él puede restaurar tu alegría.',
  'Hola 🌸! Hoy Dios quiere abrazarte.',
  'La presencia de Dios trae descanso.',
  'Dios conoce tus sueños.',
  'No estás caminando solo/a.',
  'Jesús sigue siendo luz en medio de la oscuridad.',
  'Dios quiere llenar tu vida de propósito.',
  'Cada palabra de Dios trae vida.',
  'Hoy es perfecto para fortalecer tu fe.',
  'Hola ✨! Dios sigue obrando en lo invisible.',
  'Tu devocional puede ser el inicio de algo grande.',
  'Dios puede darte paz en medio del ruido.',
  'Él nunca abandona a Sus hijos.',
  'Tu corazón merece este momento con Dios.',
  'Dios puede hacer nuevas todas las cosas.',
  'Hay poder en buscar a Dios diariamente.',
  'Hola 🙏! Jesús quiere escucharte hoy.',
  'Dios entiende tus silencios.',
  'Tu vida tiene un llamado especial.',
  'Dios sigue sosteniéndote.',
  'Él conoce tus batallas.',
  'Tu fe no es en vano.',
  'Dios puede traer orden al caos.',
  'Hoy también hay gracia para ti.',
  'Hola 💫! Acércate a Dios y encuentra descanso.',
  'Jesús sigue siendo esperanza viva.',
  'Todo cambia cuando Dios entra en escena.',
  'Hola 👋! Dios ya pensó en ti antes de que despertaras.',
  'Hoy el cielo tiene una palabra especial para tu corazón.',
  'Tu tiempo con Dios vale más de lo que imaginas.',
  'Dios puede renovar tus fuerzas hoy.',
  'Hola 🌞! Empieza tu día de la mano de Jesús.',
  'Dios sigue escribiendo milagros silenciosos.',
  'Tu alma necesita un respiro con Dios.',
  'Hay paz disponible para ti hoy.',
  'Jesús sigue siendo refugio seguro.',
  'Dios puede sanar lo que nadie más ve.',
  'Hola 💙! Dios quiere caminar contigo hoy.',
  'No temas, Dios sigue teniendo el control.',
  'Un corazón conectado con Dios nunca pelea solo.',
  'Tu devocional de hoy puede traer claridad.',
  'Dios siempre escucha tus oraciones.',
  'Hay esperanza nueva cada mañana.',
  'Hola ✨! Dios tiene planes hermosos contigo.',
  'La presencia de Dios cambia ambientes.',
  'Él sigue levantando corazones cansados.',
  'Tu fe puede crecer hoy.',
  'Dios quiere hablarte personalmente.',
  'Aún en medio del dolor, Dios permanece.',
  'Jesús nunca deja de amar.',
  'Hola 🌻! Hoy es un gran día para acercarte a Dios.',
  'Él conoce cada pensamiento de tu corazón.',
  'Dios sigue obrando aunque no lo notes.',
  'Tu historia tiene propósito.',
  'Dios puede darte descanso verdadero.',
  'Hola 🙌! La gracia de Dios es suficiente para hoy.',
  'Dios tiene una promesa para ti.',
  'Él sigue siendo fiel en todo tiempo.',
  'Un momento con Dios puede transformar tu día.',
  'Hola 💖! Jesús quiere darte paz.',
  'Dios conoce tus lágrimas.',
  'Hoy puedes empezar de nuevo.',
  'Tu vida tiene valor para Dios.',
  'Él nunca se olvida de ti.',
  'Hola 🌈! Dios sigue haciendo caminos.',
  'La oración abre puertas.',
  'Jesús quiere llenar tu corazón de esperanza.',
  'Dios puede traer calma a tu mente.',
  'No estás solo/a en esta batalla.',
  'Hola ☀️! Busca primero a Dios hoy.',
  'Él puede darte fuerzas nuevas.',
  'Tu fe mueve el corazón de Dios.',
  'Dios sigue siendo tu refugio.',
  'Hoy puede ser un día de milagros.',
  'Hola 💫! Dios quiere compartir tiempo contigo.',
  'La Biblia tiene alimento para tu alma.',
  'Dios sigue sosteniéndote incluso cuando te sientes débil.',
  'Jesús puede transformar cualquier situación.',
  'Tu tiempo devocional nunca pasa desapercibido para Dios.',
  'Dios quiere darte sabiduría para hoy.',
  'Hola 🌟! La luz de Cristo sigue brillando en ti.',
  'Él conoce tus sueños más profundos.',
  'Tu corazón necesita escuchar Su voz.',
  'Dios sigue obrando a tu favor.',
  'Hay descanso en la presencia de Dios.',
  'Hola 💙! Dale unos minutos a quien dio todo por ti.',
  'Dios puede restaurar lo que parecía roto.',
  'Tu fe está creciendo cada día.',
  'Jesús sigue llamándote por tu nombre.',
  'Dios nunca abandona a Sus hijos.',
  'Hola 🌸! Hoy es un buen día para orar.',
  'Él puede darte paz en medio de la tormenta.',
  'Todo lo puedes en Cristo que te fortalece.',
  'Dios quiere llenar tu vida de propósito.',
  'La esperanza en Dios nunca decepciona.',
  'Hola 🙏! Dios quiere escucharte hoy.',
  'Cada versículo puede fortalecer tu corazón.',
  'Jesús sigue siendo el camino.',
  'Dios puede traer alegría a tu alma.',
  'Hoy también hay misericordias nuevas.',
  'Hola ✨! Dios sigue trabajando en ti.',
  'Él conoce tus luchas silenciosas.',
  'Tu oración sí tiene impacto.',
  'Dios puede darte dirección clara.',
  'Hoy es perfecto para volver a confiar.',
  'Hola 🌻! Papito Dios te espera con amor.',
  'La presencia de Dios trae seguridad.',
  'Él puede convertir tus heridas en testimonio.',
  'Tu devocional es una inversión eterna.',
  'Dios quiere darte fortaleza.',
  'Hola 💫! Jesús sigue siendo esperanza viva.',
  'Nada es imposible para Dios.',
  'Él sigue obrando en lo invisible.',
  'Tu vida tiene un propósito divino.',
  'Dios quiere abrazar tu corazón.',
  'Hola ☀️! Hoy Dios quiere hablar contigo.',
  'Él puede llenar tus vacíos.',
  'Tu fe puede vencer el miedo.',
  'Dios sigue peleando tus batallas.',
  'Jesús puede darte descanso verdadero.',
  'Hola 🌈! La bondad de Dios te acompaña.',
  'Dios conoce el camino que debes tomar.',
  'Él nunca deja de amarte.',
  'Hoy puedes acercarte confiadamente a Dios.',
  'Hola 💖! Tu alma merece este momento especial.',
  'Dios tiene algo hermoso preparado para ti.',
  'Dios sigue haciendo nuevas todas las cosas.',
  'Hola 👋! Un momento con Dios puede cambiar tu perspectiva.',
  'Él conoce tus pensamientos antes de que hables.',
  'Tu día comienza mejor con Jesús.',
  'Dios quiere llenar tu corazón de paz.',
  'Hola 🌞! Hay esperanza fresca para ti hoy.',
  'Él sigue guiando tus pasos.',
  'La Biblia tiene respuestas para tu vida.',
  'Jesús nunca llega tarde.',
  'Hola 💙! Dios está más cerca de lo que imaginas.',
  'Tu alma necesita este descanso espiritual.',
  'Dios sigue restaurando corazones.',
  'Hoy puede ser el comienzo de algo nuevo.',
  'Él puede darte fuerzas sobrenaturales.',
  'Hola ✨! Dios quiere compartir tiempo contigo.',
  'Tu fe no está sola.',
  'Dios sigue escuchando cada oración.',
  'Él puede traer calma a tus pensamientos.',
  'Hola 🌸! Dios quiere renovar tu alegría.',
  'Tu vida tiene propósito eterno.',
  'Dios puede transformar tus lágrimas en victoria.',
  'Jesús sigue siendo refugio seguro.',
  'Hoy es un buen día para confiar nuevamente.',
  'Hola 🌻! Dios tiene una palabra para tu corazón.',
  'Él nunca te soltará.',
  'Tu tiempo con Dios produce fruto.',
  'Dios quiere enseñarte algo hoy.',
  'Jesús sigue obrando en silencio.',
  'Hola 🙌! Acércate a Dios y encuentra descanso.',
  'Él puede sanar lo que duele en secreto.',
  'Tu corazón merece paz.',
  'Dios sigue levantando al cansado.',
  'Hay amor infinito esperándote.',
  'Hola 💫! Dios quiere caminar contigo paso a paso.',
  'Él conoce tus necesidades.',
  'Tu devocional puede traer claridad a tu mente.',
  'Dios nunca se equivoca contigo.',
  'Jesús sigue siendo suficiente.',
  'Hola ☀️! Dale prioridad a tu alma hoy.',
  'Dios puede abrir caminos inesperados.',
  'Él está contigo incluso en los días difíciles.',
  'Tu oración tiene poder.',
  'Dios sigue cuidando cada detalle.',
  'Hola 🌈! Hay gracia nueva para este día.',
  'Él puede darte sabiduría en cada decisión.',
  'Tu relación con Dios vale la pena.',
  'Jesús sigue llamándote con amor.',
  'Hoy también puedes descansar en Dios.',
  'Hola 💖! Nunca es tarde para acercarte a Jesús.',
  'Dios sigue escribiendo historias de esperanza.',
  'Hola 🌟! Hoy puedes escuchar la voz de Dios.',
  'Él nunca deja de trabajar en tu vida.',
  'Tu fe puede crecer incluso en la espera.',
  'Dios quiere regalarte paz interior.',
  'Hola 🙏! Papito Dios quiere compartir contigo hoy.',
  'Él puede transformar tus preocupaciones.',
  'Tu corazón necesita alimento espiritual.',
  'Dios sigue siendo fiel a Sus promesas.',
  'Hoy puede ser un día de renovación.',
  'Hola 💙! Dios conoce exactamente lo que necesitas.',
  'Él sigue sanando corazones heridos.',
  'Tu devocional fortalece tu espíritu.',
  'Dios quiere mostrarte Su amor.',
  'Jesús sigue siendo tu mejor amigo.',
  'Hola ✨! Nunca subestimes el poder de orar.',
  'Él puede darte descanso emocional.',
  'Dios sigue sosteniendo tus pasos.',
  'Hoy puedes volver a empezar con esperanza.',
  'Hola 🌻! La presencia de Dios trae vida.',
  'Él conoce tus luchas internas.',
  'Tu tiempo con Dios no es en vano.',
  'Dios puede abrir puertas nuevas.',
  'Jesús quiere abrazar tu corazón.',
  'Hola 🌸! Hoy hay misericordias nuevas para ti.',
  'Él sigue iluminando caminos oscuros.',
  'Tu fe tiene valor eterno.',
  'Dios puede darte dirección.',
  'La paz de Dios supera todo entendimiento.',
  'Hola 💫! Haz una pausa y habla con Jesús.',
  'Él nunca se cansa de escucharte.',
  'Tu alma merece este tiempo especial.',
  'Dios sigue siendo refugio en medio del caos.',
  'Hoy puedes descansar en Sus brazos.',
  'Hola ☀️! Dios tiene algo hermoso preparado.',
  'Él puede darte fortaleza en medio de la debilidad.',
  'Tu oración mueve el cielo.',
  'Dios sigue cuidando de tu futuro.',
  'Jesús sigue siendo luz en la oscuridad.',
  'Hola 🌈! Hay esperanza incluso en los días difíciles.',
  'Él conoce tus sueños y anhelos.',
  'Tu relación con Dios transforma tu vida.',
  'Dios puede traer orden a tu mente.',
  'Hoy es un gran día para buscar a Dios.',
  'Hola 💖! Dios sigue peleando tus batallas.',
  'Él puede renovar tus fuerzas como las águilas.',
  'Tu devocional puede traer sanidad.',
  'Dios sigue escribiendo milagros silenciosos.',
  'Jesús nunca deja de amarte.',
  'Hola 🌟! Tu alma necesita unos minutos con Dios.',
  'Hoy Dios quiere hablar directamente a tu corazón.',
  'Hola 👋! No enfrentes el día sin hablar con Jesús.',
  'Él puede llenar de paz tu mente cansada.',
  'Tu fe es más fuerte de lo que piensas.',
  'Dios sigue siendo bueno contigo.',
  'Hola 🌞! Un nuevo día, una nueva oportunidad para acercarte a Dios.',
  'Él conoce cada carga que llevas.',
  'Tu devocional puede darte fuerzas inesperadas.',
  'Dios quiere recordarte cuánto te ama.',
  'Hola 💙! Jesús está contigo en cada paso.',
  'Él puede sanar lo que escondes en silencio.',
  'Tu tiempo con Dios nunca es desperdiciado.',
  'Dios sigue guiando tu camino.',
  'Hay descanso disponible para ti hoy.',
  'Hola ✨! Papá Dios te espera con los brazos abiertos.',
  'Él puede transformar tus temores en fe.',
  'Tu alma necesita este momento especial.',
  'Dios sigue haciendo caminos donde no los ves.',
  'Hoy puedes confiar nuevamente.',
  'Hola 🌸! Dios tiene promesas vivas para ti.',
  'Él nunca deja de escuchar tus oraciones.',
  'Tu corazón merece la paz de Dios.',
  'Jesús sigue siendo esperanza para tu vida.',
  'Dios puede renovar tu alegría.',
  'Hola 🌻! Acércate a Dios y encuentra descanso.',
  'Él puede darte claridad en medio de la confusión.',
  'Tu vida tiene propósito eterno.',
  'Dios sigue levantando corazones cansados.',
  'Hoy es perfecto para fortalecer tu relación con Dios.',
  'Hola 🙌! Dios está obrando incluso ahora.',
  'Él puede darte sabiduría para tus decisiones.',
  'Tu fe puede mover montañas.',
  'Dios sigue cuidando de ti.',
  'Jesús puede traer calma a tu tormenta.',
  'Hola 💫! Tu devocional de hoy puede marcar la diferencia.',
  'Él conoce tus pensamientos más profundos.',
  'Tu oración tiene poder delante de Dios.',
  'Dios puede traer luz a tus dudas.',
  'Nunca es tarde para buscar a Jesús.',
  'Hola ☀️! Dios quiere compartir contigo este momento.',
  'Él puede sanar tus heridas emocionales.',
  'Tu alma necesita alimento espiritual.',
  'Dios sigue sosteniendo tu vida.',
  'Hoy también hay gracia suficiente.',
  'Hola 🌈! La presencia de Dios cambia ambientes.',
  'Él nunca abandona a Sus hijos.',
  'Tu tiempo devocional produce fruto eterno.',
  'Dios puede darte paz verdadera.',
  'Jesús sigue siendo fiel.',
  'Hola 💖! Dios tiene algo especial preparado para ti hoy.',
  'Tu relación con Dios puede crecer hoy.',
  'Hola 🌟! Dale a Dios los primeros minutos de tu día.',
  'Él conoce tus luchas y aun así te ama.',
  'Dios puede renovar tu esperanza.',
  'Tu fe está siendo fortalecida.',
  'Hola 🙏! Dios quiere escucharte hablar hoy.',
  'Él sigue obrando aunque no lo notes.',
  'Tu corazón necesita este encuentro con Dios.',
  'Dios puede convertir pruebas en testimonios.',
  'Hoy es un buen día para volver a creer.',
  'Hola 💙! Jesús quiere darte descanso para tu alma.',
  'Él puede llenar tus vacíos internos.',
  'Tu oración nunca cae en saco roto.',
  'Dios sigue siendo tu refugio.',
  'Hoy puedes experimentar Su paz.',
  'Hola ✨! Papito Dios está esperando compartir contigo.',
  'Él puede traer alegría a tu corazón.',
  'Tu devocional puede darte dirección.',
  'Dios sigue siendo fiel a Su palabra.',
  'Jesús quiere caminar contigo hoy.',
  'Hola 🌸! Hay nuevas misericordias para ti.',
  'Él puede fortalecer tu espíritu.',
  'Tu alma merece este tiempo de descanso.',
  'Dios sigue escribiendo historias hermosas.',
  'Hoy puedes encontrar respuestas en Su palabra.',
  'Hola 🌻! Dios tiene cuidado de cada detalle.',
  'Él conoce tus sueños y tus miedos.',
  'Tu vida tiene valor eterno.',
  'Dios puede traer calma a tus pensamientos.',
  'Jesús sigue siendo luz en la oscuridad.',
  'Él nunca deja de acompañarte.',
  'Tu fe tiene más poder del que imaginas.',
  'Dios sigue levantando al que se siente débil.',
  'Hoy puedes descansar en Sus promesas.',
  'Hola ☀️! Dios quiere renovar tu mente.',
  'Él puede abrir caminos imposibles.',
  'Tu tiempo con Dios transforma tu interior.',
  'Dios sigue obrando en silencio.',
  'Jesús nunca deja de amarte.',
  'Hola 🌈! Hay esperanza viva para ti.',
  'Él puede sanar tus emociones.',
  'Tu relación con Dios vale cada minuto.',
  'Dios puede darte fortaleza para seguir.',
  'Hoy es perfecto para acercarte más a Jesús.',
  'Hola 💖! Dios sigue peleando por ti.',
  'Él conoce cada lágrima que has derramado.',
  'Tu devocional puede cambiar tu perspectiva.',
  'Dios sigue sosteniendo tus pasos.',
  'Hola 🌟! Recuerda: no estás solo/a.',
  'Dios sigue llamándote con amor.',
  'Hola 👋! Jesús quiere compartir este momento contigo.',
  'Él puede darte paz en medio de cualquier situación.',
  'Tu fe puede vencer la ansiedad.',
  'Dios sigue guiando tu camino.',
  'Hola 🌞! Un nuevo día para caminar con Dios.',
  'Él conoce tus pensamientos y te entiende.',
  'Tu alma necesita alimento espiritual.',
  'Dios puede restaurar tus fuerzas.',
  'Hola 💙! Hoy también hay gracia para ti.',
  'Él nunca deja de escuchar tus oraciones.',
  'Tu tiempo con Dios fortalece tu corazón.',
  'Dios sigue siendo esperanza segura.',
  'Jesús puede traer calma a tu vida.',
  'Hola ✨! Haz una pausa y escucha a Dios.',
  'Él puede transformar tu tristeza en alegría.',
  'Tu relación con Dios es lo más importante.',
  'Dios sigue obrando detrás de escena.',
  'Hoy puedes volver a confiar.',
  'Hola 🌸! Dios quiere renovar tu espíritu.',
  'Él puede darte dirección clara.',
  'Tu oración tiene valor eterno.',
  'Dios sigue cuidando de ti.',
  'Jesús nunca abandona a Sus hijos.',
  'Hola 🌻! Hoy es un gran día para orar.',
  'Él conoce tus cargas y quiere ayudarte.',
  'Tu fe está creciendo cada día.',
  'Dios puede darte descanso verdadero.',
  'Hay paz disponible en Su presencia.',
  'Hola 🙌! Dios quiere hablar a tu corazón.',
  'Él puede sanar lo que otros no ven.',
  'Tu devocional de hoy puede darte claridad.',
  'Dios sigue haciendo milagros silenciosos.',
  'Jesús sigue siendo suficiente.',
  'Hola 💫! Dale prioridad a tu alma hoy.',
  'Él puede darte fortaleza sobrenatural.',
  'Tu vida tiene propósito divino.',
  'Dios sigue siendo fiel.',
  'Hoy puedes descansar en Sus brazos.',
  'Hola ☀️! Dios tiene palabras de vida para ti.',
  'Él nunca llega tarde.',
  'Tu corazón necesita este momento especial.',
  'Dios puede traer orden a tu caos.',
  'Jesús quiere darte esperanza.',
  'Hola 🌈! Dios sigue obrando a tu favor.',
  'Él conoce cada batalla que enfrentas.',
  'Tu fe no es en vano.',
  'Dios puede abrir nuevas puertas.',
  'Hoy también puedes encontrar paz.',
  'Hola 💖! Dios está contigo incluso ahora.',
  'Tu devocional puede darte fuerzas para continuar.',
  'Hola 🌟! Dios tiene algo hermoso preparado para hoy.',
  'Él puede iluminar tus decisiones.',
  'Tu tiempo con Dios nunca se pierde.',
  'Dios sigue renovando corazones.',
  'Hola 🙏! Jesús quiere escucharte hoy.',
  'Él puede transformar tus pensamientos.',
  'Tu relación con Dios trae vida.',
  'Dios puede darte calma en la tormenta.',
  'Hoy es perfecto para volver a empezar.',
  'Hola 💙! La presencia de Dios trae descanso.',
  'Él sigue siendo refugio seguro.',
  'Tu alma merece ser cuidada.',
  'Dios puede darte nuevas fuerzas.',
  'Jesús sigue caminando contigo.',
  'Hola ✨! Dios conoce tus necesidades antes de pedirlas.',
  'Él puede llenar tu corazón de esperanza.',
  'Tu oración tiene poder.',
  'Dios sigue sosteniendo tu vida.',
  'Hoy puedes experimentar Su amor.',
  'Hola 🌸! Papá Dios te espera con alegría.',
  'Él puede restaurar lo que parecía perdido.',
  'Tu fe puede crecer hoy.',
  'Dios sigue obrando en cada detalle.',
  'Jesús puede darte dirección.',
  'Hola 🌻! Nunca es tarde para buscar a Dios.',
  'Él conoce tu corazón profundamente.',
  'Tu devocional puede cambiar tu día.',
  'Dios puede traer paz a tus pensamientos.',
  'Hoy hay misericordias nuevas para ti.',
  'Hola 💫! Dios quiere compartir tiempo contigo.',
  'Él nunca se olvida de ti.',
  'Tu relación con Dios fortalece tu interior.',
  'Dios sigue peleando tus batallas.',
  'Jesús sigue siendo luz en tu camino.',
  'Hola ☀️! Acércate a Dios y encuentra descanso.',
  'Él puede darte sabiduría para avanzar.',
  'Tu alma necesita escuchar Su voz.',
  'Dios sigue siendo bueno.',
  'Hoy puedes confiar una vez más.',
  'Hola 🌈! La esperanza en Dios nunca falla.',
  'Él puede sanar tu corazón cansado.',
  'Tu tiempo devocional produce paz.',
  'Dios puede hacer nuevas todas las cosas.',
  'Jesús sigue llamándote con amor.',
  'Hola 💖! Hoy Dios quiere abrazarte.',
  'Él conoce tus silencios.',
  'Tu fe puede mover montañas.',
  'Dios sigue guiando cada paso.',
  'Hola 🌟! Tu alma también necesita alimentarse.',
  'Hola 👋 Dios sigue esperándote hoy.',
  'Empieza el día con Dios y todo cambiará.',
  'Tu Biblia aún está esperando ser abierta.',
  'Jesús quiere pasar tiempo contigo hoy.',
  'Dios tiene una palabra para ti hoy.',
  'Tu tiempo con Dios también importa.',
  'Haz una pausa y habla con Jesús.',
  'Papito Dios preparó este momento para ti.',
  'Aún estás a tiempo de buscar a Dios.',
  'Dios quiere abrazar tu corazón hoy.',
  'Tu devocional puede darte la paz que necesitas.',
  'Jesús sigue esperando por ti con amor.',
  'Dios tiene algo hermoso que decirte.',
  'Unos minutos con Dios pueden cambiar tu día.',
  'Tu alma necesita este tiempo especial.',
  'Hola 🌞 Jesús quiere caminar contigo hoy.',
  'Dios sigue tocando la puerta de tu corazón.',
  'Tu espíritu también necesita alimento.',
  'Papá Dios quiere escucharte.',
  'Hoy Dios preparó una palabra solo para ti.',
  'Jesús te espera con los brazos abiertos.',
  'Tu corazón necesita descansar en Dios.',
  'Dios sigue esperando este momento contigo.',
  'Dios quiere darte fuerzas nuevas.',
  'Tu día mejora cuando empiezas con Jesús.',
  'Dios quiere hablarte personalmente.',
  'El cielo está esperando tu oración.',
  'Tu fe también necesita atención diaria.',
  'Dios sigue siendo prioridad.',
  'Jesús quiere llenar tu día de paz.',
  'Dios sigue esperándote con paciencia.',
  'Papito Dios quiere compartir contigo.',
  'Tu devocional puede traer claridad a tu mente.',
  'Dios quiere renovar tu corazón.',
  'Hoy también necesitas escuchar Su voz.',
  'Jesús sigue esperando este momento especial.',
  'Haz silencio y escucha a Dios.',
  'Tu alma necesita descansar en Su presencia.',
  'Dios preparó este día contigo en mente.',
  'Hola ✨ Dios aún te espera.',
  'No te olvides de quien nunca se olvida de ti.',
  'Tu relación con Dios merece tiempo.',
  'Papá Dios tiene un banquete espiritual para ti.',
  'Hoy puedes acercarte nuevamente a Jesús.',
  'Jesús quiere darte descanso hoy.',
  'Dios sigue disponible para escucharte.',
  'Tu corazón necesita este momento.',
  'Dios quiere renovar tus fuerzas.',
  '¿Qué tal un momento especial con Dios?',
  'Jesús sigue llamándote con amor.',
  'Tu tiempo devocional puede cambiar tu ánimo.',
  'Dios sigue esperando tu oración.',
  'Hola 🌸 Dios quiere hablarte hoy.',
  'El mejor momento del día puede ser con Dios.',
  'Jesús te espera con paciencia y amor.',
  'Dios quiere darte paz verdadera.',
  'Hoy Dios tiene respuestas para ti.',
  'Dios quiere caminar contigo este día.',
  'Tu alma merece este descanso espiritual.',
  'Jesús quiere escuchar cómo estuvo tu día.',
  'Dios tiene nuevas misericordias para ti.',
  'Tu espíritu necesita alimento hoy.',
  'Papito Dios extraña pasar tiempo contigo.',
  'Dios sigue tocando suavemente tu corazón.',
  'Hola 💫 ¿Listo/a para un momento con Jesús?',
  'Tu fe crece cada vez que buscas a Dios.',
  'Dios quiere darte dirección hoy.',
  'Jesús sigue esperando este encuentro.',
  'Dios quiere renovar tu mente.',
  'Tu relación con Dios necesita constancia.',
  'Hoy es perfecto para hablar con Jesús.',
  'Dios tiene algo especial preparado para ti.',
  'Jesús quiere darte fuerzas nuevas.',
  'Haz espacio para Dios hoy.',
  'Tu corazón necesita escuchar esperanza.',
  'Dios sigue siendo refugio seguro.',
  'Hoy también puedes descansar en Él.',
  'Papá Dios sigue esperando en la mesa.',
  'Tu alma necesita respirar a través de Dios.',
  'Jesús quiere llenar tu corazón de paz.',
  'Dios quiere compartir contigo este momento.',
  'Tu Biblia extraña tus manos.',
  'Dios sigue despierto pensando en ti.',
  'Hoy puede comenzar mejor con Dios.',
  'Haz una pausa y vuelve a Jesús.',
  'Papito Dios tiene una palabra para ti.',
  'Dios quiere escucharte hoy.',
  'Tu corazón necesita descanso espiritual.',
  'Jesús sigue esperando tu oración.',
  'El cielo sigue esperando tu voz.',
  'Dios quiere llenar tu día de esperanza.',
  'Tu fe necesita unos minutos hoy.',
  'Dios sigue tocando tu corazón.',
  'Jesús quiere caminar contigo.',
  'Dale a Dios una parte de tu día.',
  'Tu alma merece atención.',
  'Dios quiere abrazarte hoy.',
  'Aún hay tiempo para acercarte a Dios.',
  'Jesús tiene paz para tu mente.',
  'Dios sigue esperando este encuentro especial.',
  'Tu devocional puede cambiar tu perspectiva.',
  'Papito Dios preparó este momento contigo.',
  'Jesús quiere escuchar tu voz.',
  'Hoy Dios quiere darte claridad.',
  'Tu alma también necesita cuidado.',
  'Dios sigue siendo fiel contigo.',
  'Haz una pausa y busca a Jesús.',
  'Tu corazón necesita escuchar verdad.',
  'Dios quiere renovar tu esperanza.',
  'Jesús sigue siendo refugio seguro.',
  'Dios quiere compartir contigo hoy.',
  'Tu espíritu necesita fortalecerse.',
  'Papá Dios sigue esperando con amor.',
  'Tu fe puede crecer hoy.',
  'Hola 💙 Dios quiere hablarte.',
  'Jesús quiere darte descanso verdadero.',
  'Tu relación con Dios importa.',
  'Dios tiene paz disponible para ti.',
  'Hoy Dios quiere tocar tu corazón.',
  'Tu devocional puede darte fuerzas.',
  'Jesús sigue esperando tu compañía.',
  'Dios preparó algo hermoso para ti.',
  'Tu alma necesita este momento con Dios.',
  'Jesús quiere llenar tu corazón hoy.',
  'Dios sigue llamándote con amor.',
  'Tu día puede cambiar con una oración.',
  'Hoy Dios quiere renovar tu mente.',
  'Jesús sigue siendo tu refugio.',
  'Tu espíritu necesita alimento.',
  'Dios quiere escucharte en secreto.',
  'Hola ✨ Haz espacio para Dios hoy.',
  'Tu corazón necesita paz verdadera.',
  'Papito Dios tiene algo que enseñarte.',
  'Tu fe merece atención diaria.',
  'Dios sigue cuidando de ti.',
  'Hoy también hay misericordias nuevas.',
  'Jesús quiere compartir este día contigo.',
  'Tu alma necesita descanso espiritual.',
  'Dios sigue esperando tu oración.',
  'Tu devocional puede darte esperanza.',
  'Papá Dios quiere caminar contigo.',
  'Jesús tiene palabras de vida para ti.',
  'Dios quiere fortalecer tu corazón.',
  'Tu tiempo con Jesús vale mucho.',
  'Dios sigue llamando a tu puerta.',
  'Hoy puedes volver a empezar con Dios.',
  'Jesús quiere darte claridad.',
  'Tu espíritu necesita conectarse con Dios.',
  'Papito Dios extraña tus conversaciones.',
  'Dios quiere darte descanso hoy.',
  'Jesús sigue listo para escucharte.',
  'Dios quiere llenar tu día de paz.',
  'Tu alma merece unos minutos con Dios.',
  'Hoy es un gran día para orar.',
  'Papá Dios quiere abrazar tu corazón.',
  'Tu fe puede crecer hoy.',
  'Dios sigue teniendo tiempo para ti.',
  'Jesús quiere renovar tu esperanza.',
  'Tu corazón necesita escuchar a Dios.',
  'Dios quiere hablarte personalmente.',
  'Hoy puedes descansar en Su amor.',
  'Jesús sigue siendo suficiente.',
  'Tu alma necesita alimento celestial.',
  'Dios aún te espera con amor.',
];

export const RECORDATORIOS_MAÑANA: string[] = [
  'No olvides alimentar tu espíritu.',
  'No olvides hablar con Papá Dios hoy.',
  'Hola 💫! No olvides hablar con Dios hoy.',
  'Aún no haces tu devocional 😢 Papá Dios te extraña.',
  'No olvides alimentar tu alma.',
  'No termines el día sin hablar con Jesús.',
  '¿Ya hablaste con Dios hoy?',
  'No ignores la voz de Dios hoy.',
  'No dejes pasar este encuentro con Dios.',
  'Aún no es tarde para hacer tu devocional.',
  'Hola 💙 ¿Le regalarás unos minutos a Dios?',
  'No olvides conectar con quien más te ama.',
  '¿Ya sacaste tiempo para Dios hoy?',
];

export const RECORDATORIOS_TARDE: string[] = [
  'No ignores ese deseo de acercarte a Dios.',
  'No pases el día lejos de Dios.',
  'No olvides darle prioridad a tu alma.',
  'Tu devocional te está esperando.',
  'No ignores el llamado de Jesús.',
  'Aún puedes tomar unos minutos para Dios.',
  'No olvides abrir tu corazón a Dios.',
  'No termines el día sin agradecer a Dios.',
  'No olvides buscar primero a Dios.',
  'Aún no haces tu devocional 😢 Jesús te espera.',
  'No ignores el alimento de tu alma.',
  'Hola 🌞 ¿Ya hablaste con Dios?',
  'No dejes tu devocional para después.',
];

export const RECORDATORIOS_NOCHE: string[] = [
  'No olvides alimentar tu espíritu.',
  'No ignores la invitación de Dios.',
  'Aún puedes acercarte a Dios hoy.',
  'No termines el día sin orar.',
  'No olvides tu tiempo especial con Jesús.',
  'Aún no haces tu devocional 👀 Dios sigue esperando.',
  'No olvides hablar con Papá Dios.',
  'No pases el día lejos de Jesús.',
  'No ignores la voz suave de Dios.',
  'No olvides buscar primero a Dios.',
  'No termines el día sin Su presencia.',
  'Tu devocional te está esperando 📖',
  'No olvides abrir la Biblia hoy.',
];

// Obtener frase motivacional del día (basada en día del año para ser consistente)
export function getFraseDelDia(date: Date = new Date()): string {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  const index = (dayOfYear * 24 + date.getHours()) % FRASES_MOTIVACIONALES.length;
  return FRASES_MOTIVACIONALES[index] ?? FRASES_MOTIVACIONALES[0]!;
}

// Obtener recordatorio aleatorio según el turno del día
export function getRecordatorio(turno: 'mañana' | 'tarde' | 'noche'): string {
  const pool =
    turno === 'mañana'
      ? RECORDATORIOS_MAÑANA
      : turno === 'tarde'
        ? RECORDATORIOS_TARDE
        : RECORDATORIOS_NOCHE;
  const idx = Math.floor(Math.random() * pool.length);
  return pool[idx] ?? pool[0]!;
}
